# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  twitter_api_key: 'evkewxLv9aI0YfvylKNv2LHRn'
  twitter_api_secret: 'KXD5dhFvDgflpvllsygmxaL10sqWPLd6uQPyHvKxBriEYsdXac'

development:
  secret_key_base: 2341b7fe434d38c5878cf7f098ab89188832e6d1087e37550bfe7897703696cf19fc9e65b4d969161455b532ee8cd15993dd8121330d2cbc60bee617344bee8a
  <<: *default_twitter

test:
  secret_key_base: d5fe67fc8df91e949c947ab7bd42f6ba4eda0087619aa8a714fe4f3741a2f0d0d2ad4990bb8fb171f13f6ff769db3256d5d4c0e01bbdbd450a8bc1ad5ce544d5
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
